# -*- coding: utf-8 -*-
"""CSC492DataCleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-pl3yku6wd8j6qB5bkwUWp22eGuGPu9a
"""

# Cleaning Data
# import stuff
import pandas as pd
from pandas import *

# read csv
Data = read_csv('Transfer_Courses.csv')

# function to fix course code column
def FixCourseCode(Col):
  NewColumnList = []
  for i in Col:
    i = str(i)
    # get rid of spaces in course codes
    NSCrsCde = i.replace(' ','')
    # capitalize all letters in course codes
    CNSCrsCde = NSCrsCde.upper()
    NewColumnList.append(CNSCrsCde)
  # return our new list of fixed course codes
  return NewColumnList

# check that our function is working
#print(FixCourseCode(Data['Unnamed: 3']))
#print(len(Data['Unnamed: 3'].unique()))
#print(len(unique(FixCourseCode(Data['Unnamed: 3']))))

DataFrame = pd.DataFrame(FixCourseCode(Data['Unnamed: 3']), columns=['New Course Codes'])
# can insert other data from CSV using this
#DataFrame.insert(0,'Transfer Courses',Data['Transfer Courses'])
print(DataFrame)

# attempt to figure out how many entries are unique
#count = 0
#for i in range(0,len(Data)):
#  for j in range(0,len(Data)):
#    if Data.iloc[[i,2]] == Data.iloc[[j,2]]:
#      if Data.iloc[[i,3]] == Data.iloc[[j,3]]:
#        pass
#    else:
#      count += 1
#print(count)